### ISSUE TITLE
Application labels aren't unique, duplicates: bootstrap3

### ISSUE THREAD

**Issue by holms** [django-admin-bootstrapped/django-admin-bootstrapped#124]
Guys, seems that you have a conflict with other cool django app installed: https://github.com/dyve/django-bootstrap3

```
    django@apgavo:~/apgavo$ python manage.py collectstatic
    Traceback (most recent call last):
      File "manage.py", line 10, in <module>
        execute_from_command_line(sys.argv)
      File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
        utility.execute()
      File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 354, in execute
        django.setup()
      File "/usr/local/lib/python2.7/dist-packages/django/__init__.py", line 21, in setup
        apps.populate(settings.INSTALLED_APPS)
      File "/usr/local/lib/python2.7/dist-packages/django/apps/registry.py", line 89, in populate
        "duplicates: %s" % app_config.label)
    django.core.exceptions.ImproperlyConfigured: Application labels aren't unique, duplicates: bootstrap3
```

settings.py:

```
    INSTALLED_APPS = (
        'django_admin_bootstrapped.bootstrap3',
        'django_admin_bootstrapped',
        'django.contrib.admin',
        'django.contrib.auth',
        'django.contrib.contenttypes',
        'django.contrib.sessions',
        'django.contrib.messages',
        'django.contrib.staticfiles',
        'django_extensions',
        'bootstrap3',
    )
```

**Comment by mjrulesamrat** [comment]
I'm building project with django-oscar. I have to modify the customer view by extending it.
When I do so then I get this error.."django.core.exceptions.ImproperlyConfigured: Application labels aren't unique, duplicates: customer".
Can you help to solve this?
Thanks

**Comment by xrmx** [comment]
@mjrulesamrat The error means you have two apps called customer, see 82d90e96464e55eed9004a2f9e99a1504abc64a7 for how we fixed this. Said that better ask this kind of questions in the proper support mediums https://docs.djangoproject.com/en/1.7/faq/help/

**Comment by PamelaQuatix** [comment]
fggdgdg

**Comment by Vishal8236** [comment]
Same issue here.

django.core.exceptions.ImproperlyConfigured: Application labels aren't unique, duplicates: sessions
