### ISSUE TITLE
TemplateSyntaxError in the admin panel

### ISSUE THREAD

**Issue by abhijithanilkumar** [django-admin-bootstrapped/django-admin-bootstrapped#245]
Clicking `Change Password` and `Logout` in the admin panel raises the following error : 

```python
Traceback (most recent call last):
  File "/home/abhijith/venv/councilwebsite/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 177, in __call__
    response = self.get_response(request)
  File "/home/abhijith/venv/councilwebsite/lib/python2.7/site-packages/django/core/handlers/base.py", line 230, in get_response
    response = self.handle_uncaught_exception(request, resolver, sys.exc_info())
  File "/home/abhijith/venv/councilwebsite/lib/python2.7/site-packages/django/core/handlers/base.py", line 289, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File "/home/abhijith/Code/NITK-Student-Council-Website/src/Student_Council_Website/wsgi.py", line 24, in null_technical_500_response
    six.reraise(exc_type, exc_value, tb)
  File "/home/abhijith/venv/councilwebsite/lib/python2.7/site-packages/django/core/handlers/base.py", line 174, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/abhijith/venv/councilwebsite/lib/python2.7/site-packages/django/core/handlers/base.py", line 172, in get_response
    response = response.render()
  File "/home/abhijith/venv/councilwebsite/lib/python2.7/site-packages/django/template/response.py", line 160, in render
    self.content = self.rendered_content
  File "/home/abhijith/venv/councilwebsite/lib/python2.7/site-packages/django/template/response.py", line 135, in rendered_content
    template = self._resolve_template(self.template_name)
  File "/home/abhijith/venv/councilwebsite/lib/python2.7/site-packages/django/template/response.py", line 90, in _resolve_template
    new_template = self.resolve_template(template)
  File "/home/abhijith/venv/councilwebsite/lib/python2.7/site-packages/django/template/response.py", line 82, in resolve_template
    return get_template(template, using=self.using)
  File "/home/abhijith/venv/councilwebsite/lib/python2.7/site-packages/django/template/loader.py", line 32, in get_template
    return engine.get_template(template_name, dirs)
  File "/home/abhijith/venv/councilwebsite/lib/python2.7/site-packages/django/template/backends/django.py", line 40, in get_template
    return Template(self.engine.get_template(template_name, dirs), self)
  File "/home/abhijith/venv/councilwebsite/lib/python2.7/site-packages/django/template/engine.py", line 190, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "/home/abhijith/venv/councilwebsite/lib/python2.7/site-packages/django/template/engine.py", line 157, in find_template
    name, template_dirs=dirs, skip=skip,
  File "/home/abhijith/venv/councilwebsite/lib/python2.7/site-packages/django/template/loaders/base.py", line 46, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/home/abhijith/venv/councilwebsite/lib/python2.7/site-packages/django/template/base.py", line 189, in __init__
    self.nodelist = self.compile_nodelist()
  File "/home/abhijith/venv/councilwebsite/lib/python2.7/site-packages/django/template/base.py", line 230, in compile_nodelist
    return parser.parse()
  File "/home/abhijith/venv/councilwebsite/lib/python2.7/site-packages/django/template/base.py", line 514, in parse
    raise self.error(token, e)
TemplateSyntaxError: 'url' is not a valid tag or filter in tag library 'future'
```

I'm using Django 1.9.

**Comment by adamteale** [comment]
I´m also experiencing the same error and using Django 1.9

**Comment by kolanos** [comment]
url was removed from future in Django 1.9 and url has been included in templates by default for quite some time.

**Comment by a3gisknight** [comment]
#233 identified the same issue and was closed because it got fixed on December of 2015. So the current code in github is right, but after a pip install, the code it wrong. Maybe the pip package isn't up to date?

**Comment by xrmx** [comment]
@a3gisknight thanks for noticing. Closing as dup of #233.
